apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  #type: NodePort
  type: ClusterIP
  selector:
    app: trivial-go-web-app
  ports:
    #- nodePort: 32000
    - name: http-service
      protocol: TCP
      port: 8081
